### Q1: Recommender System

##### 1. Download m1.zip file from the link (https://grouplens.org/datasets/movielens/1m/) (0
points)
#### 2. Load the movies and ratings data. (2 points)

In [15]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
import numpy.linalg as nla
import scipy.linalg as sla
from scipy.linalg import svd as SVD

In [16]:
mov_df = pd.read_csv('movies.csv')
user_df = pd.read_csv('users.csv')
rating_df = pd.read_csv('ratings.csv')

In [17]:
mov_df.head()

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [18]:
mov_df.shape

(3883, 3)

In [19]:
user_df.head()

user_id sex  age_group  occupation zip_code
0        1   F          1          10    48067
1        2   M         56          16    70072
2        3   M         25          15    55117
3        4   M         45           7    02460
4        5   M         25          20    55455

In [20]:
user_df.shape

(6040, 5)

In [21]:
rating_df.head()

user_id  movie_id  rating  unix_timestamp
0        1      1193       5       978300760
1        1       661       3       978302109
2        1       914       3       978301968
3        1      3408       4       978300275
4        1      2355       5       978824291

#### Create m x u matrix with movies as row and users as column. Normalize the matrix.

In [24]:
rating_mat = np.ndarray(shape = (np.max(rating_df['movie_id'].values), np.max(rating_df['user_id'].values)))
rating_mat[rating_df['movie_id'].values -1, rating_df['user_id'].values -1] = rating_df['rating'].values 
print(rating_mat)

[[5. 0. 0. ... 0. 0. 3.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
rating_mat.shape

(3952, 6040)

In [41]:
matrix_normed = normalize(rating_mat, axis=1, norm='l1')
print(matrix_normed)

[[0.00058052 0.         0.         ... 0.         0.         0.00034831]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [42]:
row_sums = np.sum(matrix_normed, axis=1)
print(row_sums)

[1. 1. 1. ... 1. 1. 1.]


#### Perform SVD to get U, S and V.

In [48]:
A = matrix_normed.T
print(A)

[[0.00058052 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.00034831 0.         0.         ... 0.         0.         0.        ]]


In [50]:
U, S, V = np.linalg.svd(A)
U.shape, S.shape, V.shape

((6040, 6040), (3952,), (3952, 3952))

In [51]:
print(U)

[[-4.03211148e-06  3.94696623e-05  1.43577314e-04 ... -3.63563369e-03
  -6.93699812e-03 -6.21288098e-03]
 [-1.70718808e-05  1.23713797e-04  2.70641594e-04 ...  8.63829169e-03
  -2.07468351e-03  5.33051125e-03]
 [-5.85749580e-06  1.10134600e-05  5.58688119e-05 ...  5.35450589e-03
   9.61481093e-03  9.99005767e-03]
 ...
 [-1.63670731e-06  8.61401415e-06  4.30527981e-05 ...  7.47984705e-01
  -7.13953154e-03  8.88845257e-03]
 [-2.14810738e-05  1.62837020e-04  3.74611932e-04 ... -1.05134569e-02
   3.01048842e-01  6.54963656e-04]
 [-2.44140751e-04  5.23861699e-04  6.86569428e-03 ... -4.94067902e-03
   3.12437400e-04  7.21498646e-02]]


In [52]:
print(V)

[[-3.33319115e-05 -8.02622133e-05 -3.50995230e-04 ... -2.43627864e-03
  -5.20896109e-03 -5.23522655e-04]
 [ 1.88110378e-04  6.31878835e-04  5.76221538e-04 ...  4.27648981e-03
  -2.02509142e-05  9.89450008e-04]
 [ 9.64656588e-04  1.66922086e-03  1.32396779e-03 ...  4.20538843e-03
   1.30243733e-02  2.39507689e-03]
 ...
 [ 0.00000000e+00 -4.37094402e-16  3.87974651e-16 ... -1.55998548e-16
  -8.85188811e-17 -1.72485505e-16]
 [ 0.00000000e+00 -1.17001508e-16 -1.48320364e-16 ... -3.35365857e-17
  -3.62711561e-17  8.16090132e-17]
 [ 0.00000000e+00  1.77414513e-16 -5.56443192e-18 ...  5.87925097e-17
   5.85755516e-17  1.45364405e-17]]


In [55]:
print(S)

[5.13788244e+00 3.85596761e+00 2.06454852e+00 ... 1.61950746e-16
 1.19475111e-16 5.93542094e-17]


In [58]:
sigma = np.zeros((6040,3952))
for i in range(3952):
    sigma[i,i] = S[i]
print(sigma)

[[5.13788244 0.         0.         ... 0.         0.         0.        ]
 [0.         3.85596761 0.         ... 0.         0.         0.        ]
 [0.         0.         2.06454852 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


#### Select top 50 components from S.

In [59]:
S50 = sigma[0:50,0:50]
print(S50)

[[5.13788244 0.         0.         ... 0.         0.         0.        ]
 [0.         3.85596761 0.         ... 0.         0.         0.        ]
 [0.         0.         2.06454852 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.03481653 0.         0.        ]
 [0.         0.         0.         ... 0.         1.03053352 0.        ]
 [0.         0.         0.         ... 0.         0.         1.02655154]]


In [67]:
U50 = U[:,0:50]


In [68]:
V50 =V[0:50,:]


In [69]:
AR50 = U50@S50@V50
print(np.round(AR50))
print(AR50.shape)
print(AR50.size)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(6040, 3952)
23870080


In [71]:
sum_AR50 = np.sum(AR50, axis=0)
print(sum_AR50)

[0.31582416 0.52541022 0.50171779 ... 0.80427646 0.75985252 0.4770868 ]


#### Get the top 50 eigenvectors using eigenvalues.

In [60]:
evalue, evector = nla.eig(S50)

In [61]:
print(evalue)

[5.13788244 3.85596761 2.06454852 2.04435496 1.85810519 1.75067804
 1.64074475 1.44704454 1.42337725 1.41776456 1.39306009 1.36952962
 1.30358371 1.27411695 1.24157848 1.22749739 1.21303681 1.19285992
 1.18765024 1.17157347 1.1311292  1.12554549 1.1235695  1.12045272
 1.11165203 1.10731128 1.10009881 1.09820568 1.09591631 1.09048052
 1.08946895 1.08508885 1.07906155 1.07654567 1.06608221 1.06163458
 1.05860387 1.05490193 1.05294556 1.05242908 1.05070974 1.05004651
 1.04465721 1.04399889 1.04034985 1.03872047 1.038236   1.03481653
 1.03053352 1.02655154]


In [62]:
evalue.size

50

In [63]:
print(evector)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [64]:
evector_50 = np.diag(evector)
print(evector_50)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


#### Using cosine similarity, find 10 closest movies using the 50 components from SVD.

In [77]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a movie-user matrix named 'ratings_matrix'
# Replace this with your actual movie-user matrix

# Perform SVD
svd = TruncatedSVD(n_components=50)
print(svd)
svd_matrix = svd.fit_transform(A)
print(svd_matrix.shape)
# Calculate cosine similarity
cosine_sim = cosine_similarity(svd_matrix, svd_matrix)

# Find 10 closest movies for each movie
closest_movies = {}
for i, movie_row in enumerate(cosine_sim):
    closest_movies[i] = sorted(enumerate(movie_row), key=lambda x: x[1], reverse=True)[1:11]

# Display the results
for movie_id, closest in closest_movies.items():
    print(f"\nClosest movies to Movie {movie_id + 1}:")
    for close_movie_id, similarity in closest:
        print(f"Movie {close_movie_id + 1}, Similarity: {similarity:.4f}")

TruncatedSVD(n_components=50)
(6040, 50)

Closest movies to Movie 1:
Movie 1476, Similarity: 0.9475
Movie 4890, Similarity: 0.9469
Movie 5759, Similarity: 0.9454
Movie 2353, Similarity: 0.9446
Movie 551, Similarity: 0.9439
Movie 3936, Similarity: 0.9435
Movie 5713, Similarity: 0.9429
Movie 3989, Similarity: 0.9423
Movie 2597, Similarity: 0.9410
Movie 1232, Similarity: 0.9400

Closest movies to Movie 2:
Movie 4322, Similarity: 0.9707
Movie 1301, Similarity: 0.9643
Movie 6003, Similarity: 0.9624
Movie 5643, Similarity: 0.9607
Movie 4482, Similarity: 0.9606
Movie 2585, Similarity: 0.9572
Movie 903, Similarity: 0.9570
Movie 1074, Similarity: 0.9568
Movie 3108, Similarity: 0.9564
Movie 5677, Similarity: 0.9563

Closest movies to Movie 3:
Movie 2664, Similarity: 0.9853
Movie 3208, Similarity: 0.9848
Movie 3773, Similarity: 0.9839
Movie 913, Similarity: 0.9835
Movie 2436, Similarity: 0.9832
Movie 3432, Similarity: 0.9830
Movie 2394, Similarity: 0.9820
Movie 3281, Similarity: 0.9806
Movie 1983

In [ ]:
import numpy as np
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have a movie-user matrix named 'ratings_matrix'
# Replace this with your actual movie-user matrix

# Perform SVD
svd = TruncatedSVD(n_components=50)
print(svd)
svd_matrix = svd.fit_transform(A)
print(svd_matrix.shape)
# Calculate cosine similarity
cosine_sim = cosine_similarity(svd_matrix, svd_matrix)

# Find 10 closest movies for each movie
closest_movies = {}
for i, movie_row in enumerate(cosine_sim):
    closest_movies[i] = sorted(enumerate(movie_row), key=lambda x: x[1], reverse=True)[1:11]

# Display the results
for movie_id, closest in closest_movies.items():
    print(f"\nClosest movies to Movie {movie_id + 1}:")
    for close_movie_id, similarity in closest:
        print(f"Movie {close_movie_id + 1}, Similarity: {similarity:.4f}")